from __future__ import annotations

# Semantic component graph for Refoundation Epoch 0.  These are intentionally
# not historical Part/R labels.  Aggregate state owners coexist with smaller
# independently versioned subcomponents where the accepted implementation
# already has meaningful internal boundaries.
COMPONENT_SPECS: tuple[tuple[str, str, str, str, tuple[str, ...]], ...] = (
    ("core.canonical_digest", "core", "canonical JSON, digest and content identity", "canonical-digest-v1", ()),
    ("schemas.identity", "schemas", "stable identity/rank/status/namespace schemas", "identity-schema-v1", ("core.canonical_digest",)),
    ("organization.identity", "organization", "67 permanent identity registry", "organization-identity-v1", ("schemas.identity",)),
    ("organization.authority", "organization", "authoritative ownership, block and override graph", "authority-v1", ("organization.identity",)),
    ("organization.events", "organization", "append-only causal cognitive events", "events-v1", ("organization.identity", "core.canonical_digest")),
    ("organization.lifecycle", "organization", "persistent wake/sleep/checkpoint lifecycle", "lifecycle-v1", ("organization.identity", "organization.events")),
    ("external.artifacts", "external_core", "content-addressed immutable artifact fabric", "artifacts-v1", ("organization.identity", "core.canonical_digest")),
    ("external.evidence", "external_core", "verification evidence references and subjects", "evidence-v1", ("external.artifacts", "organization.identity")),
    ("organization.tasks", "organization", "task DAG and execution projection", "tasks-v1", ("organization.identity", "organization.events", "organization.authority")),
    ("organization.coordination.leases", "organization", "canonical-target lease epoch and heartbeat authority", "coordination-leases-v1", ("organization.tasks",)),
    ("organization.coordination.delivery", "organization", "causal event delivery and ACK transport", "coordination-delivery-v1", ("organization.events",)),
    ("organization.coordination.conflicts", "organization", "artifact-authority conflict coordination", "coordination-conflicts-v1", ("organization.authority", "organization.events")),
    ("organization.coordination", "organization", "aggregate bounded coordination state", "coordination-v1", ("organization.coordination.leases", "organization.coordination.delivery", "organization.coordination.conflicts", "organization.lifecycle")),
    ("external.requirements", "external_core", "requirement DAG, constraints and acceptance revisions", "requirements-v1", ("organization.authority", "external.evidence")),
    ("external.planning", "external_core", "Master Plan DAG, milestones, risks and revisions", "master-plan-v1", ("external.requirements", "organization.authority")),
    ("external.architecture", "external_core", "component/interface/trust/ADR/change-impact graph", "architecture-v1", ("external.requirements", "external.planning", "organization.authority")),
    ("external.integration", "external_core", "compatibility and semantic integration authority", "integration-v1", ("external.architecture", "external.evidence", "organization.authority")),
    ("external.memory.fabric", "external_core", "scoped persistent memory ledger", "memory-fabric-v1", ("external.evidence",)),
    ("external.memory.lifecycle", "external_core", "memory status and semantic relation lifecycle", "memory-lifecycle-v1", ("external.memory.fabric",)),
    ("external.memory.retrieval", "external_core", "budgeted deterministic memory selection receipts", "memory-retrieval-v1", ("external.memory.fabric",)),
    ("external.knowledge", "external_core", "provenance-aware reusable knowledge fabric", "knowledge-v1", ("external.evidence",)),
    ("external.skills", "external_core", "personal/regional/global reusable skill fabric", "skills-v1", ("external.evidence",)),
    ("external.experience", "external_core", "identity-owned learning episodes and attribution", "experience-v1", ("organization.identity",)),
    ("external.self_model", "external_core", "evidence-backed competence and calibration state", "self-model-v1", ("external.evidence",)),
    ("external.epistemic", "external_core", "hypothesis, uncertainty and epistemic workspace", "epistemic-v1", ("external.evidence",)),
    ("external.verification", "external_core", "fail-closed candidate verification primitive", "verification-v1", ("external.evidence", "organization.identity")),
    ("external.individual_evolution", "external_core", "evidence-gated per-identity skill/neural/self-model evolution", "individual-evolution-v1", ("external.skills", "external.self_model", "external.verification")),
    ("external.context", "external_core", "context providers, continuity and semantic deltas", "context-v1", ("external.memory.retrieval", "external.knowledge", "external.skills", "external.self_model", "external.planning", "external.architecture")),
    ("external.invokable_cores", "external_core", "invokable external-core schema, permission and failure registry", "invokable-cores-v1", ("organization.identity",)),
    ("external.execution.workspace", "external_core", "exact isolated repository workspace", "execution-workspace-v1", ("external.artifacts",)),
    ("external.coding.claims", "external_core", "exclusive source mutation ownership", "coding-claims-v1", ("organization.coordination.leases",)),
    ("external.execution.executor", "external_core", "side-effect membrane for tools and cores", "execution-executor-v1", ("organization.coordination.leases", "external.invokable_cores", "external.execution.workspace", "external.coding.claims")),
    ("neural.shared", "neural", "shared neural substrate and checkpoint lineage", "neural-shared-manifest-v1", ("core.canonical_digest",)),
    ("neural.inference_bridge", "neural_boundary", "versioned context-to-neural inference adapter", "neural-inference-bridge-v1", ("neural.shared", "external.context")),
    ("external.execution.control", "external_core", "bounded inference/action session loop", "execution-control-v1", ("neural.inference_bridge", "external.execution.executor")),
    ("external.coding.patches", "external_core", "patch candidates, tool receipts and evidence lineage", "coding-patches-v1", ("external.coding.claims", "external.artifacts")),
    ("external.coding.control", "external_core", "coding work routing, patch readiness and handoff", "coding-control-v1", ("external.coding.patches", "external.planning", "external.architecture", "external.integration", "external.verification")),
    ("external.debugging", "external_core", "failure reproduction, hypotheses and root-cause handoff", "debugging-v1", ("external.coding.control", "external.evidence")),
    ("external.ui_ux", "external_core", "UX authority, frontend implementation and render-quality evidence", "ui-ux-v1", ("external.coding.control", "external.artifacts", "external.evidence", "external.verification")),
    ("external.assurance", "external_core", "policy/domain independent assurance and challenges", "assurance-v1", ("external.evidence", "external.verification", "organization.authority")),
    ("external.operations", "external_core", "migration, build, release, reliability and performance readiness", "operations-v1", ("external.assurance", "external.artifacts")),
    ("external.research", "external_core", "freshness/provenance research and governed handoff", "research-v1", ("external.assurance", "external.artifacts")),
    ("external.cognitive_library", "external_core", "typed operators, abstractions, provenance descriptors and read-only fit diagnostics", "cognitive-library-v2", ("external.evidence", "external.assurance")),
    ("external.capability_acquisition", "external_core", "probation, quarantine, promotion and retrieval firewall", "capability-acquisition-v1", ("external.cognitive_library", "external.assurance")),
    ("external.candidate_synthesis", "external_core", "stateless provenance-bound capability proposal synthesis", "candidate-synthesis-v1", ("external.cognitive_library", "external.capability_acquisition", "external.evidence", "external.causal", "external.experimentation")),
    ("external.causal", "external_core", "bounded proof-carrying causal basis mechanisms", "causal-v1", ("external.cognitive_library", "external.evidence")),
    ("external.experimentation", "external_core", "active probes, interventions and version-space experiments", "experimentation-v1", ("external.causal", "external.evidence")),
    ("external.reasoning_invention", "external_core", "evidence-bound invention plus bounded epistemic frontier, Pareto metacontrol, fresh-context adversarial review and descriptive meta-learning evidence", "reasoning-invention-v1", ("external.cognitive_library", "external.candidate_synthesis", "external.causal", "external.experimentation", "external.evidence")),
    ("external.transfer_meta", "external_core", "portable verified experience and governed meta reuse", "transfer-meta-v1", ("external.causal", "external.experience", "external.assurance")),
    ("organization.temporary_work_units", "organization", "bounded Foundry-derived work units that never join permanent AgentRegistry", "temporary-work-units-v1", ("organization.identity", "organization.coordination.leases", "external.artifacts", "external.assurance", "external.skills")),
    ("evaluation.regimes", "evaluation", "frozen benchmark regime and budget contracts", "evaluation-regimes-v1", ("external.evidence",)),
    ("evaluation.evidence", "evaluation", "observations, matched-budget comparisons and ablations", "evaluation-evidence-v1", ("evaluation.regimes",)),
    ("evaluation.stress", "evaluation", "long-horizon continuity and failure stress receipts", "evaluation-stress-v1", ("evaluation.evidence",)),
    ("evaluation.parameters", "evaluation", "physical/logical parameter accounting and scaling authority", "evaluation-parameters-v1", ("organization.identity", "evaluation.evidence")),
    ("evaluation.release", "evaluation", "exact scientific evaluation release and reproduction", "evaluation-release-v1", ("evaluation.evidence", "evaluation.parameters", "external.artifacts")),
    ("evaluation.claims", "evaluation", "fail-closed scientific claim boundary", "evaluation-claims-v1", ("evaluation.release", "evaluation.stress")),
    ("evaluation.scaling", "evaluation", "aggregate evaluation and future-scaling state", "evaluation-scaling-v1", ("evaluation.regimes", "evaluation.evidence", "evaluation.stress", "evaluation.parameters", "evaluation.release", "evaluation.claims")),
    ("evaluation.campaign", "evaluation", "sealed real-repository evaluation campaign", "evaluation-campaign-v1", ("evaluation.regimes", "external.execution.control")),
    ("organization.central", "organization", "global direct-worker and governed control composition", "central-v1", ("organization.authority", "organization.tasks", "organization.coordination", "external.context", "external.invokable_cores")),
    ("organization.runtime", "organization", "manifest-driven canonical runtime assembly target", "runtime-composition-v1", ("organization.central", "organization.temporary_work_units", "external.coding.control", "external.debugging", "external.ui_ux", "external.operations", "external.research", "evaluation.scaling", "evaluation.campaign")),
)
