from __future__ import annotations

from pathlib import Path


TRANSFER = Path('cogcoder/r268_cross_task_causal_transfer.py')
SCRATCH = Path('cogcoder/r268_cross_task_transfer_baseline.py')

HELPER_ANCHOR = '''def _prediction_key(prediction: tuple[bool, object]) -> str:\n    valid, value = prediction\n    if not valid:\n        return 'invalid'\n    return json.dumps(_canonical_number(value), separators=(',', ':'), allow_nan=False)\n\n\n'''

HELPER = '''class _TrackedOracleContext(dict[str, int | float]):\n    __slots__ = ('mutation_attempted',)\n\n    def __init__(self, values: Mapping[str, int | float]) -> None:\n        super().__init__(values)\n        self.mutation_attempted = False\n\n    def __setitem__(self, key: str, value: int | float) -> None:\n        self.mutation_attempted = True\n        super().__setitem__(key, value)\n\n    def __delitem__(self, key: str) -> None:\n        self.mutation_attempted = True\n        super().__delitem__(key)\n\n    def clear(self) -> None:\n        self.mutation_attempted = True\n        super().clear()\n\n    def pop(self, key: str, *default: object) -> object:\n        self.mutation_attempted = True\n        return super().pop(key, *default)\n\n    def popitem(self) -> tuple[str, int | float]:\n        self.mutation_attempted = True\n        return super().popitem()\n\n    def setdefault(self, key: str, default: int | float = 0) -> int | float:\n        self.mutation_attempted = True\n        return super().setdefault(key, default)\n\n    def update(self, *args: object, **kwargs: int | float) -> None:\n        self.mutation_attempted = True\n        super().update(*args, **kwargs)\n\n    def __ior__(self, other: object):\n        self.mutation_attempted = True\n        return super().__ior__(other)\n\n\ndef _oracle_context_token(context: Mapping[str, object]) -> str | None:\n    try:\n        return json.dumps(dict(context), sort_keys=True, separators=(',', ':'), allow_nan=False)\n    except (TypeError, ValueError):\n        return None\n\n\ndef _call_oracle_isolated(\n    oracle: Callable[[Mapping[str, object]], object],\n    context: Mapping[str, object],\n) -> tuple[str, int | float | None, dict[str, int | float]]:\n    values = _context_values(context)\n    semantic_context = dict(zip(_PROBE_ROLES, values, strict=True))\n    oracle_context = _TrackedOracleContext(semantic_context)\n    before_token = _oracle_context_token(oracle_context)\n\n    try:\n        raw = oracle(oracle_context)\n    except (ArithmeticError, TypeError, ValueError, OverflowError, ZeroDivisionError):\n        after_token = _oracle_context_token(oracle_context)\n        if oracle_context.mutation_attempted or after_token != before_token:\n            return 'mutation', None, semantic_context\n        return 'invalid', None, semantic_context\n\n    after_token = _oracle_context_token(oracle_context)\n    if oracle_context.mutation_attempted or after_token != before_token:\n        return 'mutation', None, semantic_context\n    try:\n        observed = _canonical_number(raw)\n    except (ArithmeticError, TypeError, ValueError, OverflowError, ZeroDivisionError):\n        return 'invalid', None, semantic_context\n    return 'ok', observed, semantic_context\n\n\n'''

TRANSFER_SELECTION_OLD = '''        try:\n            observed = _canonical_number(oracle(context))\n        except (ArithmeticError, TypeError, ValueError, OverflowError, ZeroDivisionError):\n            return _failed_receipt(\n                candidates_generated=len(generated),\n                live=live,\n                selection_queries=selection_queries + 1,\n                terminal_queries=0,\n                terminal_exact=0,\n                reason='invalid_oracle_output',\n                trace=trace,\n            )\n        selection_queries += 1\n        used_keys.add(key)\n        survivors: list[TransferCandidate] = []\n        for candidate in live:\n            valid, predicted = _safe_prediction(candidate.expression, context)\n'''
TRANSFER_SELECTION_NEW = '''        oracle_status, observed, semantic_context = _call_oracle_isolated(oracle, context)\n        if oracle_status != 'ok':\n            return _failed_receipt(\n                candidates_generated=len(generated),\n                live=live,\n                selection_queries=selection_queries + 1,\n                terminal_queries=0,\n                terminal_exact=0,\n                reason=(\n                    'oracle_context_mutation'\n                    if oracle_status == 'mutation'\n                    else 'invalid_oracle_output'\n                ),\n                trace=trace,\n            )\n        selection_queries += 1\n        used_keys.add(key)\n        survivors: list[TransferCandidate] = []\n        for candidate in live:\n            valid, predicted = _safe_prediction(candidate.expression, semantic_context)\n'''

TRANSFER_TERMINAL_OLD = '''        try:\n            observed = _canonical_number(oracle(context))\n        except (ArithmeticError, TypeError, ValueError, OverflowError, ZeroDivisionError):\n            return _failed_receipt(\n                candidates_generated=len(generated),\n                live=live,\n                selection_queries=selection_queries,\n                terminal_queries=terminal_queries + 1,\n                terminal_exact=terminal_exact,\n                reason='invalid_terminal_oracle_output',\n                trace=trace,\n            )\n        terminal_queries += 1\n        survivors = []\n        for candidate in live:\n            valid, predicted = _safe_prediction(candidate.expression, context)\n'''
TRANSFER_TERMINAL_NEW = '''        oracle_status, observed, semantic_context = _call_oracle_isolated(oracle, context)\n        if oracle_status != 'ok':\n            return _failed_receipt(\n                candidates_generated=len(generated),\n                live=live,\n                selection_queries=selection_queries,\n                terminal_queries=terminal_queries + 1,\n                terminal_exact=terminal_exact,\n                reason=(\n                    'terminal_oracle_context_mutation'\n                    if oracle_status == 'mutation'\n                    else 'invalid_terminal_oracle_output'\n                ),\n                trace=trace,\n            )\n        terminal_queries += 1\n        survivors = []\n        for candidate in live:\n            valid, predicted = _safe_prediction(candidate.expression, semantic_context)\n'''

SCRATCH_IMPORT_OLD = '''    _canonical_number,\n    _choose_diagnostic,\n'''
SCRATCH_IMPORT_NEW = '''    _call_oracle_isolated,\n    _canonical_number,\n    _choose_diagnostic,\n'''

SCRATCH_SELECTION_OLD = '''        try:\n            observed = _canonical_number(oracle(context))\n        except (ArithmeticError, TypeError, ValueError, OverflowError, ZeroDivisionError):\n            return _failed_receipt(\n                candidates_generated=len(generated), live=live,\n                selection_queries=selection_queries + 1,\n                terminal_queries=0, terminal_exact=0,\n                reason='invalid_oracle_output', trace=trace,\n            )\n        selection_queries += 1\n        used_keys.add(key)\n        survivors: list[TransferCandidate] = []\n        for candidate in live:\n            valid, predicted = _safe_prediction(candidate.expression, context)\n'''
SCRATCH_SELECTION_NEW = '''        oracle_status, observed, semantic_context = _call_oracle_isolated(oracle, context)\n        if oracle_status != 'ok':\n            return _failed_receipt(\n                candidates_generated=len(generated), live=live,\n                selection_queries=selection_queries + 1,\n                terminal_queries=0, terminal_exact=0,\n                reason=(\n                    'oracle_context_mutation'\n                    if oracle_status == 'mutation'\n                    else 'invalid_oracle_output'\n                ), trace=trace,\n            )\n        selection_queries += 1\n        used_keys.add(key)\n        survivors: list[TransferCandidate] = []\n        for candidate in live:\n            valid, predicted = _safe_prediction(candidate.expression, semantic_context)\n'''

SCRATCH_TERMINAL_OLD = '''        try:\n            observed = _canonical_number(oracle(context))\n        except (ArithmeticError, TypeError, ValueError, OverflowError, ZeroDivisionError):\n            return _failed_receipt(\n                candidates_generated=len(generated), live=live,\n                selection_queries=selection_queries,\n                terminal_queries=terminal_queries + 1,\n                terminal_exact=terminal_exact,\n                reason='invalid_terminal_oracle_output', trace=trace,\n            )\n        terminal_queries += 1\n        survivors = []\n        for candidate in live:\n            valid, predicted = _safe_prediction(candidate.expression, context)\n'''
SCRATCH_TERMINAL_NEW = '''        oracle_status, observed, semantic_context = _call_oracle_isolated(oracle, context)\n        if oracle_status != 'ok':\n            return _failed_receipt(\n                candidates_generated=len(generated), live=live,\n                selection_queries=selection_queries,\n                terminal_queries=terminal_queries + 1,\n                terminal_exact=terminal_exact,\n                reason=(\n                    'terminal_oracle_context_mutation'\n                    if oracle_status == 'mutation'\n                    else 'invalid_terminal_oracle_output'\n                ), trace=trace,\n            )\n        terminal_queries += 1\n        survivors = []\n        for candidate in live:\n            valid, predicted = _safe_prediction(candidate.expression, semantic_context)\n'''


def replace_once(text: str, old: str, new: str, label: str) -> str:\n    count = text.count(old)\n    if count != 1:\n        raise SystemExit(f'{label}: expected exactly one replacement boundary, found {count}')\n    return text.replace(old, new, 1)\n

def main() -> None:\n    transfer = TRANSFER.read_text(encoding='utf-8')\n    scratch = SCRATCH.read_text(encoding='utf-8')\n\n    if '_call_oracle_isolated(' not in transfer:\n        transfer = replace_once(transfer, HELPER_ANCHOR, HELPER_ANCHOR + HELPER, 'helper')\n    transfer = replace_once(transfer, TRANSFER_SELECTION_OLD, TRANSFER_SELECTION_NEW, 'transfer selection')\n    transfer = replace_once(transfer, TRANSFER_TERMINAL_OLD, TRANSFER_TERMINAL_NEW, 'transfer terminal')\n    scratch = replace_once(scratch, SCRATCH_IMPORT_OLD, SCRATCH_IMPORT_NEW, 'scratch import')\n    scratch = replace_once(scratch, SCRATCH_SELECTION_OLD, SCRATCH_SELECTION_NEW, 'scratch selection')\n    scratch = replace_once(scratch, SCRATCH_TERMINAL_OLD, SCRATCH_TERMINAL_NEW, 'scratch terminal')\n\n    TRANSFER.write_text(transfer, encoding='utf-8')\n    SCRATCH.write_text(scratch, encoding='utf-8')\n    print('R268T_ORACLE_CONTEXT_ISOLATION_MATERIALIZED')\n

if __name__ == '__main__':\n    main()\n