from pathlib import Path

runtime=Path('cogcoder/_r268_runtime.py')
text=runtime.read_text()
old="""    max_basis_size=int(max_basis_size);per_basis=int(composition_max_candidates_per_basis);max_total=int(max_composition_candidates_total)\n    if max_basis_size<1 or per_basis<1 or max_total<1:raise ValueError('basis size and candidate budgets must be positive')\n    oracle_calls=0;queried=set()\n"""
new="""    max_basis_size=int(max_basis_size);per_basis=int(composition_max_candidates_per_basis);max_total=int(max_composition_candidates_total)\n    if max_basis_size<1 or per_basis<1 or max_total<1:raise ValueError('basis size and candidate budgets must be positive')\n\n    # Validation is independent authority evidence. Materialize every semantic\n    # oracle input this runtime would actually query before the first oracle\n    # call: base contexts plus all legal intervention applications. Preserve a\n    # multiset/list for within-validation uniqueness and sets for cross-phase\n    # disjointness. This invariant lives here so private-runtime callers cannot\n    # bypass the public API authority boundary.\n    specs=enumerate_interventions(schema.field_names,tuple(map(float,anchor_values)),arity=int(intervention_arity))\n    prepared_specs=[]\n    discovery_query_keys={context_key(schema,row) for row in discovery}\n    validation_query_keys=[context_key(schema,row) for row in validation]\n    for spec in specs:\n        ad=tuple(spec.apply(r,schema.field_names) for r in discovery);av=tuple(spec.apply(r,schema.field_names) for r in validation)\n        if context_validator is not None and any(not bool(context_validator(r)) for r in (*ad,*av)):continue\n        prepared_specs.append((spec,ad,av))\n        discovery_query_keys.update(context_key(schema,row) for row in ad)\n        validation_query_keys.extend(context_key(schema,row) for row in av)\n    validation_key_set=set(validation_query_keys)\n    if len(validation_key_set)!=len(validation_query_keys):\n        raise ValueError(\n            'validation oracle query inputs must be semantically unique '\n            f'(duplicate_count={len(validation_query_keys)-len(validation_key_set)})'\n        )\n    overlap=discovery_query_keys & validation_key_set\n    if overlap:\n        raise ValueError(\n            'discovery and validation oracle-query universes must be semantically disjoint '\n            f'(overlap_count={len(overlap)})'\n        )\n\n    oracle_calls=0;queried=set()\n"""
if text.count(old)!=1: raise SystemExit(f'guard anchor count != 1: {text.count(old)}')
text=text.replace(old,new,1)
old="""    specs=enumerate_interventions(schema.field_names,tuple(map(float,anchor_values)),arity=int(intervention_arity));profiles=[]\n    for spec in specs:\n        ad=tuple(spec.apply(r,schema.field_names) for r in discovery);av=tuple(spec.apply(r,schema.field_names) for r in validation)\n        if context_validator is not None and any(not bool(context_validator(r)) for r in (*ad,*av)):continue\n        dv=[];vv=[]\n"""
new="""    profiles=[]\n    for spec,ad,av in prepared_specs:\n        dv=[];vv=[]\n"""
if text.count(old)!=1: raise SystemExit(f'profile anchor count != 1: {text.count(old)}')
runtime.write_text(text.replace(old,new,1))

public=Path('cogcoder/r268_adaptive_causal_basis.py')
public.write_text("""from __future__ import annotations\nfrom ._r268_proof import (\n    build_basis_collision_certificate,\n    build_public_target_collision_certificate,\n    verify_basis_collision_certificate,\n    verify_necessity_certificate,\n)\nfrom ._r268_runtime import discover_adaptive_causal_basis,synthesize_adaptive_causal_basis\nfrom ._r268_types import AdaptiveCausalBasisCandidate,AdaptiveCausalBasisReceipt,AdaptiveCausalBasisStructureReceipt,BasisCollisionCertificate,NecessityCertificate\n\n__all__=[\n    'NecessityCertificate','BasisCollisionCertificate','AdaptiveCausalBasisCandidate','AdaptiveCausalBasisStructureReceipt','AdaptiveCausalBasisReceipt',\n    'build_basis_collision_certificate','verify_basis_collision_certificate','build_public_target_collision_certificate','verify_necessity_certificate',\n    'discover_adaptive_causal_basis','synthesize_adaptive_causal_basis',\n]\n""")
print('R268_COMBINED_PRIVATE_QUERY_AUTHORITY_APPLIED')
